# Generated by Django 5.2 on 2025-04-29 07:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='input_videos/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('output_video', models.FileField(blank=True, null=True, upload_to='output/')),
                ('summary_json', models.FileField(blank=True, null=True, upload_to='output/')),
                ('object_tracks_json', models.FileField(blank=True, null=True, upload_to='output/tracks/')),
                ('keypoint_tracks_json', models.FileField(blank=True, null=True, upload_to='output/tracks/')),
                ('all_tracks_json', models.FileField(blank=True, null=True, upload_to='output/tracks/')),
            ],
        ),
    ]
