# Generated by Django 5.2 on 2025-04-29 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_processor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='all_tracks_json',
        ),
    ]
