# Generated by Django 5.2 on 2025-05-02 01:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_processor', '0002_remove_video_all_tracks_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_image', models.FileField(blank=True, null=True, upload_to='output/events/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_frames', to='video_processor.video')),
            ],
        ),
    ]
