# Generated by Django 5.2 on 2025-05-02 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_processor', '0003_eventframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventframe',
            name='frame_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
