# Generated by Django 5.2 on 2025-05-01 14:26

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='team_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='experience_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Enthusiast', 'Enthusiast'), ('Pro', 'Pro')], default=datetime.datetime(2025, 5, 1, 19, 26, 8, 43104), max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default=datetime.datetime(2025, 5, 1, 19, 26, 19, 708649), max_length=15),
            preserve_default=False,
        ),
    ]
